version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: own-ng-lib
    path: ""
    text-resources:
      - path: "*.html"
        format: angular-hardcoded
